package com.isdemir.isdemirdb.entity;

import com.fasterxml.jackson.annotation.JsonProperty;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

// Maps the malzeme_tablosu table. @JsonProperty keeps the JSON field names unchanged.
@Entity
@Table(name = "\"malzeme_Tanim\"")   // buyuk harf -> tirnakli
@Getter
@Setter
@NoArgsConstructor
public class Material {

    // malzeme_id is generated by a DB sequence (identity)
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "malzeme_id")
    @JsonProperty("malzemeId")
    private Integer id;

    @Column(name = "malzeme_kodu")
    @JsonProperty("malzemeKodu")
    private Integer code;

    // Additive group: KONVKATKI, POTAKATKI, HURDAKATKI ...
    @Column(name = "malzeme_turu")
    @JsonProperty("malzemeTuru")
    private String type;

    @Column(name = "malzeme_adi")
    @JsonProperty("malzemeAdi")
    private String name;

    @Column(name = "aktif_pasif")
    @JsonProperty("aktifPasif")
    private Boolean active;
}
