-- Baseline schema, captured from the existing `isdemir` database (PostgreSQL 18.4).
-- This is the starting point every environment builds from. Do not edit this file:
-- schema changes go in a new V<n>__*.sql migration.
--
-- PostgreSQL database dump
--






--
-- Name: dokum_tablosu; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.dokum_tablosu (
    dokum_id integer NOT NULL,
    dokum_no integer NOT NULL,
    konverter_no integer NOT NULL,
    hurda_sarj_baslama_zamani timestamp without time zone,
    hurda_sarj_bitis_zamani timestamp without time zone,
    ana_uflemeye_baslama_zamani timestamp without time zone,
    ana_ufleme_bitis_zamani timestamp without time zone,
    dokum_zamani timestamp without time zone,
    shd_sicaklik integer,
    dokum_sicaklik integer,
    lans_skal_durum character varying(20),
    kayit_zamani timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    kullanici_id integer,
    CONSTRAINT chk_lans_skal_durum CHECK (((lans_skal_durum)::text = ANY ((ARRAY['AZ_SKALLI'::character varying, 'ORTA_SKALLI'::character varying, 'COK_SKALLI'::character varying])::text[]))),
    CONSTRAINT dokum_tablosu_dokum_sicaklik_check CHECK (((dokum_sicaklik >= 1500) AND (dokum_sicaklik <= 1700))),
    CONSTRAINT dokum_tablosu_shd_sicaklik_check CHECK (((shd_sicaklik >= 1200) AND (shd_sicaklik <= 1500)))
);


--
-- Name: kullanici; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.kullanici (
    kullanici_id integer NOT NULL,
    kullanici_adi character varying(50) NOT NULL,
    kullanici_parola character varying(72) NOT NULL,
    rol_adi character varying(20)
);


--
-- Name: kullanici_kullanici_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.kullanici ALTER COLUMN kullanici_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.kullanici_kullanici_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: malzeme_kullanim_alani; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.malzeme_kullanim_alani (
    kullanim_id integer NOT NULL,
    dokum_id integer NOT NULL,
    malzeme_kodu integer CONSTRAINT malzeme_kullanim_alani_malzeme_id_not_null NOT NULL,
    miktar integer,
    malzeme_verilis_tarihi timestamp without time zone,
    kullanici_id integer,
    islem_zamani timestamp without time zone DEFAULT LOCALTIMESTAMP NOT NULL
);


--
-- Name: malzeme_kullanim_alani_kullanim_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.malzeme_kullanim_alani ALTER COLUMN kullanim_id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.malzeme_kullanim_alani_kullanim_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: malzeme_tablosu; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.malzeme_tablosu (
    malzeme_id integer NOT NULL,
    malzeme_kodu integer,
    malzeme_turu character varying(100),
    malzeme_adi character varying(255),
    aktif_pasif boolean DEFAULT true
);


--
-- Name: malzeme_tablosu_malzeme_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.malzeme_tablosu_malzeme_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: malzeme_tablosu_malzeme_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.malzeme_tablosu_malzeme_id_seq OWNED BY public.malzeme_tablosu.malzeme_id;


--
-- Name: refresh_tokens; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.refresh_tokens (
    id bigint NOT NULL,
    kullanici_id bigint NOT NULL,
    token text NOT NULL,
    bitis_zamani timestamp without time zone NOT NULL,
    olusturulma_zamani timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    aktif boolean DEFAULT true NOT NULL
);


--
-- Name: refresh_tokens_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.refresh_tokens_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: refresh_tokens_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.refresh_tokens_id_seq OWNED BY public.refresh_tokens.id;


--
-- Name: malzeme_tablosu malzeme_id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.malzeme_tablosu ALTER COLUMN malzeme_id SET DEFAULT nextval('public.malzeme_tablosu_malzeme_id_seq'::regclass);


--
-- Name: refresh_tokens id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.refresh_tokens ALTER COLUMN id SET DEFAULT nextval('public.refresh_tokens_id_seq'::regclass);


--
-- Name: dokum_tablosu dokum_tablosu_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dokum_tablosu
    ADD CONSTRAINT dokum_tablosu_pkey PRIMARY KEY (dokum_id);


--
-- Name: kullanici kullanici_kullanici_adi_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.kullanici
    ADD CONSTRAINT kullanici_kullanici_adi_key UNIQUE (kullanici_adi);


--
-- Name: kullanici kullanici_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.kullanici
    ADD CONSTRAINT kullanici_pkey PRIMARY KEY (kullanici_id);


--
-- Name: malzeme_kullanim_alani malzeme_kullanim_alani_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.malzeme_kullanim_alani
    ADD CONSTRAINT malzeme_kullanim_alani_pkey PRIMARY KEY (kullanim_id);


--
-- Name: malzeme_tablosu malzeme_tablosu_malzeme_kodu_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.malzeme_tablosu
    ADD CONSTRAINT malzeme_tablosu_malzeme_kodu_key UNIQUE (malzeme_kodu);


--
-- Name: malzeme_tablosu malzeme_tablosu_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.malzeme_tablosu
    ADD CONSTRAINT malzeme_tablosu_pkey PRIMARY KEY (malzeme_id);


--
-- Name: refresh_tokens refresh_tokens_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.refresh_tokens
    ADD CONSTRAINT refresh_tokens_pkey PRIMARY KEY (id);


--
-- Name: dokum_tablosu uq_dokum_no; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dokum_tablosu
    ADD CONSTRAINT uq_dokum_no UNIQUE (dokum_no);


--
-- Name: malzeme_kullanim_alani fk_dokum_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.malzeme_kullanim_alani
    ADD CONSTRAINT fk_dokum_id FOREIGN KEY (dokum_id) REFERENCES public.dokum_tablosu(dokum_id);


--
-- Name: dokum_tablosu fk_kullanici_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dokum_tablosu
    ADD CONSTRAINT fk_kullanici_id FOREIGN KEY (kullanici_id) REFERENCES public.kullanici(kullanici_id);


--
-- Name: malzeme_kullanim_alani fk_kullanici_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.malzeme_kullanim_alani
    ADD CONSTRAINT fk_kullanici_id FOREIGN KEY (kullanici_id) REFERENCES public.kullanici(kullanici_id);


--
-- Name: malzeme_kullanim_alani fk_malzeme_kodu; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.malzeme_kullanim_alani
    ADD CONSTRAINT fk_malzeme_kodu FOREIGN KEY (malzeme_kodu) REFERENCES public.malzeme_tablosu(malzeme_kodu);


--
-- Name: refresh_tokens fk_refresh_tokens_kullanici; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.refresh_tokens
    ADD CONSTRAINT fk_refresh_tokens_kullanici FOREIGN KEY (kullanici_id) REFERENCES public.kullanici(kullanici_id) ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--


